# This config file is templatized so that it can be easily customized. Values can be provided with a values.yml at the root of this repository
template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  # Sample Go app in a GitRepo
  - name: git_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      branches:
        include: main
      gitProvider: {{ .Values.gitProvider }}

  - name: cron_trigger_cu
    type: CronTrigger
    configuration:
      interval: '0 2 1 * *'


pipelines:
  - name: AzureCustodian
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: SetupCustodian
        type: Bash
        configuration:
          inputResources:
            - name: git_repo
            - name: cron_trigger_cu
        execution:
          onStart:
            - sudo apt-get update -y
            - sudo apt-get install -y  apt-utils python3-venv
            - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            - python3 -m venv custodian-runtime
            - source custodian-runtime/bin/activate
            - pip install c7n c7n_azure
              
          onExecute:
            - pwd
            - custodian -h
            - cd ./dependencyState/resources/git_repo/custodian-pipeline
            - export AZURE_TENANT_ID="0d768803-cf68-4acc-a0a2-b3744df7da0b"
            - export AZURE_SUBSCRIPTION_ID="9ca4b1d3-1d91-4022-9dc7-9cd240fc1237"
            - export AZURE_CLIENT_ID="d3066ae9-cf5a-4cb4-b219-296f8a568510"
            - export AZURE_CLIENT_SECRET="2w.8Q~BK7FSM~_Y3F.lpTBXP12ENZIvQNFG.cbHL"
            - export AZURE_USE_MSI=1
            - custodian run -s . azurevm.yml
            - custodian report -s . --format=grid --field "tags=tags" azurevm.yml
              
