# This config file is templatized so that it can be easily customized. Values can be provided with a values.yml at the root of this repository
template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  # Sample Go app in a GitRepo
  - name: git_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      branches:
        include: main
      gitProvider: {{ .Values.gitProvider }}

  - name: cron_trigger_cu
    type: CronTrigger
    configuration:
      interval: '0 2 1 * *'


pipelines:
  - name: AzureCustodian
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: SetupCustodian
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger_cu
        execution:
          onExecute:
            - sudo apt-get update -y
#             - sudo apt-get install -y  apt-utils python3-venv
            - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#             - python3 -m venv custodian-runtime
#             - source custodian-runtime/bin/activate
            - pip3 install c7n c7n_azure
            - custodian -h
      - name: RunPolicies
          type: Bash
          configuration:
            inputSteps:
              - name: SetupCustodian
            inputResources:
              - name: git_repo
          execution:              
            onExecute:
              - custodian -h
              - cd ./dependencyState/resources/git_repo/custodian-pipeline
              - export AZURE_TENANT_ID=$int_CustodianAzure_TenantId
              - export AZURE_SUBSCRIPTION_ID=$int_CustodianAzure_SubscriptionId
              - export AZURE_CLIENT_ID=$int_CustodianAzure_ClientId
              - export AZURE_CLIENT_SECRET=$int_CustodianAzure_ClientSecret
              - export AZURE_USE_MSI=1
              - custodian run -s . azurevm.yml
              - custodian report -s . --format=grid --field "tags=tags" azurevm.yml
